#!/bin/bash

BACKUP_SOURCE=/
BACKUP_MOUNT=/backup

function usage() {
  echo "Usage: ${0} backup /dev/sdc4"
  exit 0
}

if [ "${1}" == "" ]; then
  usage
fi

BACKUP_DEVICE=${1}

if [ ! -d "${BACKUP_MOUNT}" ]; then
  mkdir ${BACKUP_MOUNT}
fi

echo "Starting backup: `date`" >> ~/backup.log
cryptsetup open ${BACKUP_DEVICE} backup
mount /dev/mapper/backup ${BACKUP_MOUNT}
rsync -aAXv --delete --exclude=/dev/*        \
                     --exclude=/proc/*       \
                     --exclude=/sys/*        \
                     --exclude=/tmp/*        \
                     --exclude=/run/*        \
                     --exclude=/mnt/*        \
                     --exclude=/backup/*     \
                     --exclude=/lost+found/* \
                     --exclude="Downloads"   \
                     --exclude=.cache        \
                     --exclude=/shared/*     ${BACKUP_SOURCE} ${BACKUP_MOUNT} >> ~/backup.log 2>&1
umount ${BACKUP_MOUNT}
cryptsetup close backup
echo "Ending backup: `date`" >> ~/backup.log
